Increment3 use chi frameworks onboard
sashganush/shortcut pull request #4
Opened 2022-02-14 18:15 UTC by sashganush

Chi framework was added before in Increment1

2022-02-15 06:55 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	r.Post("/", func(w http.ResponseWriter, r *http.Request) {
можно просто сделать, обертка в функцию никакого бенефита здесь не несет)
```
r.Post("/", internal.PostRequestHandler); 
```

2022-02-15 06:55 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	r.Get("/{id}", func(w http.ResponseWriter, r *http.Request) {
аналогично предыдущему комменту)

2022-02-15 06:55 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	http.ListenAndServe(":8080", r)
можем порт вынести в константу

2022-02-15 06:57 UTC, sergeysergeevru commented on internal/app/shortener/handlers.go
> +	rand.Seed(time.Now().UnixNano())
все верно, сид нужно прокидывать один раз на этапе инициализации, 👍

2022-02-15 07:01 UTC, sergeysergeevru commented on internal/app/shortener/handlers.go
> +	fmt.Fprintf(w, "http://localhost:8080/%s", newURL)
в реальной жизни адрес может меняться, можем унести "http://localhost:8080" в константу

2022-02-15 07:06 UTC, sergeysergeevru commented on internal/app/shortener/handlers.go
> +	if s, exists := allRedirects[strings.TrimPrefix(r.URL.Path, "/")]; exists {
у chi мы можем вытянуть ID из path через обертку, можешь глянуть документацию как это сделать.

2022-02-15 07:10 UTC, sergeysergeevru commented on internal/app/shortener/storage.go
> +const SHORTURLLEN = 10
Комьюнити предпочитает camel case в константах -> `ShortURLLen` как-то так стоит написать. В любом случае сейчас это смотрится не сильно читаемо.

2022-02-15 07:12 UTC, sergeysergeevru commented on internal/app/shortener/storage.go
> +	"4444": "https://google.com/abcd",
объявление мапы как глобальной переменной ок, но вот данные туда кидать таким образом не стоит. Если это используется для тестирования, то унеси добавление данных в тесты.

2022-02-15 07:14 UTC, sergeysergeevru commented on internal/app/shortener/handlers_test.go
> +	type want struct {
давай покроем больше функционала тестами: проверим ручку отвечающую за создание урла, может какие-нибудь граничные условия.

2022-02-15 07:16 UTC, sergeysergeevru commented on internal/app/shortener/handlers.go
> +	allRedirects[newURL] = string(oldURL[:])
Какая разница между `oldURL[:]` и oldURL? :)  и там и тут один и тот же результат выходит)

2022-02-15 07:17 UTC, sergeysergeevru commented on internal/app/shortener/handlers.go
> +	oldURL, err := ioutil.ReadAll(r.Body)
желательно закрывать Body поле обработки

2022-02-15 07:19 UTC, sergeysergeevru commented on internal/app/shortener/handlers.go
> +	allRedirects[newURL] = string(oldURL[:])
можешь ли ты гарантировать отсутсвие коллизий? RandStringRunes может отдать на 2 одинаковых ключа, для двух разных урлов. Может сейчас и не так важно, но в будущем желательно об этом позаботиться.

2022-02-15 07:28 UTC, sergeysergeevru commented on internal/app/shortener/handlers.go
> +}
очень похоже на мертвый код, если это так, то давай уберем. В случае каких-то аргументов готов выслушать)

2022-02-15 07:29 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	http.ListenAndServe(":8080", r)
просто пожелание залогировать ошибку, возвращаемую ListenAndServe. Пример: у меня куча сервисов на рабочей машине и я часто наталкиваюсь на то, что новый поднимаемый сервис конфликтует по портам с предыдущим. Если не залогировать ошибку, можно потерять время на понимание почему приложение не стартует.

2022-02-15 07:30 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +func TestEmpty(t *testing.T) {}
зачем нужен пустой тест?

2022-02-15 07:38 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +package main
вообще не понимаю смысла этого файла, тут только запуск TestMain в котором все скипается, да и тестов данного пакета нет. Думаю можно просто убрать, потому что тестировать в main пакете особо нечего сейчас

2022-02-15 07:39 UTC, sergeysergeevru commented on README.md
> +Инкремент 3 прошёл ничайно в первом инкременте когда искалась ошибка в обработчике
👌 не страшно)

2022-02-15 07:47 UTC, sergeysergeevru requested changes
Все хорошо, однако предлагаю причесать немного код и расширить тесты. И еще смотри, можем разобраться с директориями в internal пакете.
Или сейчас переложить все в internal/app то есть на уровень выше. Либо можешь чуток заморочиться и разделить на пакеты internal/app, internal/handlers, internal/storage. 
В настоящее время не вижу смымыла в пакете internal/app/shortener, так как shortener это и есть твой пакет. В будущем можно больше задуматься об DI, clean architecture (или хексогональной архитектуре.) Но это в будущем, пока давай просто причешем кодик. Жду доработанный код для аппрува, спасибо! 😉

2022-02-15 18:12 UTC, sashganush commented
Добрый вечер Сергей,
Спасибо за замечания всё понятно,
Всё по делу , местами заловил думал допилить красоты на днях.
ПС: По поводу тест функции на сколько помню спёр в etcd чтоб проходили тесты на мэйн
Отпишусь на гихабе и пришлю новый мр как будет готово 

Александр 


> On 15 Feb 2022, at 09:48, Sergey Sergeev ***@***.***> wrote:
> 
> ﻿
> @sergeysergeevru requested changes on this pull request.
> 
> Все хорошо, однако предлагаю причесать немного код и расширить тесты. И еще смотри, можем разобраться с директориями в internal пакете.
> Или сейчас ложить все в internal/app то есть на уровень выше. Либо можешь чуток заморочиться и разделить на пакеты internal/app, internal/handlers, internal/storage.
> В настоящее время не вижу смымыла в пакете internal/app/shortener, так как shortener это и есть твой пакет. В будущем можно больше задуматься об DI, clean architecture (или хексогональной архитектуре.) Но это в будущем, пока давай просто причешем кодик. Жду доработанный код для аппрува, спасибо! 😉
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

2022-02-20 15:08 UTC, sashganush commented on internal/app/shortener/handlers.go
> +	fmt.Fprintf(w, "http://localhost:8080/%s", newURL)
да не стал этого сразу делать, ну ок будем всю по людски сразу делать по возможности :)

2022-02-20 15:09 UTC, sashganush commented on internal/app/shortener/handlers.go
> +	if s, exists := allRedirects[strings.TrimPrefix(r.URL.Path, "/")]; exists {
этот кусок делал когда chi ещё не было в реализации - зерефакторим :)

2022-02-20 16:03 UTC, sashganush commented on internal/app/shortener/storage.go
> +	"4444": "https://google.com/abcd",
это типо статики которая зашита по умолчанию, использовал для тестирования - уберу

2022-02-20 16:05 UTC, sashganush commented on internal/app/shortener/handlers.go
> +	allRedirects[newURL] = string(oldURL[:])
да это бядя  в понимании приведения типов в golang - нашёл какойто кописпаст - поправил на предложеное

2022-02-20 16:16 UTC, sashganush commented on internal/app/shortener/handlers.go
> +	allRedirects[newURL] = string(oldURL[:])
нет не могу, было в проекте одном недавно что на 4 милиардах ключей  хешключа уже на 20 миллионах словили колизии , но думаю что с этим справимся как либо если в задаче такое будет нужно обиграть ;)

2022-02-21 16:07 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +		})
я так понимаю можно было сразу r.Get("/{ID}", handlers.GetRequestHandler) прописать. Да и внешнюю обертку в r.Route("/", func(r chi.Router) на 20 строке не очень понимаю. С точки зрения работы приложения не страшно, но выглядит лишним.

2022-02-21 16:09 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(storage.DefaultHostName+storage.DefaultHostPort, r), nil)
где-то тут что-то с форматированием. И константы я бы отдельные для сервера бы использовал. В реальном приложение может быть, что хост на котором висит приложение (допустим внутри докера на локалхосте), отличаться от хоста который отдает в сгенерированной ссылке.

2022-02-21 16:13 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	r.Body.Close()
закрытие лучше перенести перед проверкой ошибки, иначе если у тебя ошибка будет, то боди не закроется

2022-02-21 16:14 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	r.Body.Close()
а зачем ты два раза боди закрываешь? У тебя же на 39 строке есть дефер?

2022-02-21 16:16 UTC, sergeysergeevru commented on internal/storage/storage.go
> +package storage
у тебя в пакете только константы лежат. В текущем состоянии дел можно было бы оставить в handlers пакете. Если бы ты сюда мапу вынес, то могло быть логично. Сейчас логики большой не вижу. Природа констант не относится к storage.

2022-02-21 16:18 UTC, sergeysergeevru approved these changes
Хорошо 👍

2022-02-26 11:25 UTC, sashganush commented on internal/handlers/handlers.go
> +	r.Body.Close()
ругается линтер,  что не закрыто - впихнул насильно - тоже ругается - хотел бы понять что не так

2022-02-26 11:26 UTC, sashganush commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(storage.DefaultHostName+storage.DefaultHostPort, r), nil)
вообще я думал в следующем спринте добавить os.GetEnv который бы настраивал и эту штуку - поэтому пока так , а далее поправим

2022-02-26 12:27 UTC, sashganush commented on cmd/shortener/main.go
> +		})
упростил конструкцию ;)

2022-02-26 12:27 UTC, sashganush commented on internal/storage/storage.go
> +package storage
убрал как не нужное

2022-02-26 12:57 UTC, merged